apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  ports:
  - port: 8001
    name: http
  selector:
    app: consumer
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: consumer
  name: consumer-config
data:
  bootstrap.yaml: |-
    server:
      port: 8001

    spring:
      application:
        name: consumer
      cloud:
        nacos:
          discovery:
            enabled: true
            server-addr: nacos-headless:8848
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
      version: v1
  template:
    metadata:
      labels:
        app: consumer
        version: v1
    spec:
      containers:
      - name: consumer
        image: xcbeyond/consumer:v1
        imagePullPolicy: IfNotPresent
        command: ["java", "-jar", "consumer-0.0.1.jar"]
        ports:
        - containerPort: 8001