apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  selector:
    app: consumer
  ports:
    - port: 8001
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
      version: v1
  template:
    metadata:
      labels:
        app: consumer
        version: v1
    spec:
      containers:
        - name: consumer
          image: xcbeyond/consumer:v1
          imagePullPolicy: IfNotPresent
          command: [ "java", "-jar", "consumer.jar" ]
          ports:
            - containerPort: 8001