apiVersion: v1
kind: Service
metadata:
  name: provider
  labels:
    app: provider
spec:
  ports:
  - port: 8001
    name: http
  selector:
    app: provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  labels:
    app: provider
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
      version: v1
  template:
    metadata:
      labels:
        app: provider
        version: v1
    spec:
      containers:
      - name: provider
        image: xcbeyond/provider:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001