apiVersion: v1
kind: Service
metadata:
  name: provider
  labels:
    app: provider
spec:
  selector:
    app: provider
  ports:
    - port: 8002
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  labels:
    app: provider
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
      version: v1
  template:
    metadata:
      labels:
        app: provider
        version: v1
    spec:
      containers:
        - name: provider
          image: xcbeyond/provider:v1
          imagePullPolicy: IfNotPresent
          command: [ "java", "-jar", "provider.jar" ]
          ports:
            - containerPort: 8002