
name: consumer-provider Image CI

on: workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login dockerhub registry
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u xcbeyond --password-stdin

    - name: Build image
      run: |
        cd consumer-provider
        docker build -t xcbeyond/consumer:v1 --build-arg MODULE=consumer .
        docker build -t xcbeyond/provider:v1 --build-arg MODULE=provider .
        docker build -t xcbeyond/provider:v2 --build-arg MODULE=provider --build-arg VERSION=v2 .

    - name: Push image
      run: |
        docker push xcbeyond/consumer:v1
        docker push xcbeyond/provider:v1
        docker push xcbeyond/provider:v2